title: "Hanbin Lee"
email: "hanbin973@gmail.com"
description:
    "Mostly genetics and epidemiology" 
show_excerpts: true # set to true to show excerpts on the homepage


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: "Hanbin Lee" 
  tagline: Genetics. Epidemiology
  date_format: "%b %d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: HAAANBIN
    github:  hanbin973
    linkedIn: in/hanbin-lee-4b5617118
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com
    
    disqus_shortname: hanbin-lees-blog
    analytics_id: '128593793'

 #If you want to link only specific pages in your header, uncomment
 #this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
remote_theme: hanbin973/plainwhite-jekyll 

# base url
markdown: kramdown
url: https://hanbin973.github.io/

