# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Theme settings
remote_theme: thelehhman/plainwhite-jekyll

# Plainwhite settings
plainwhite:
    name: Hanbin Lee
    tagline: Genetics, Epidemiology
    date_format: "%b %-d, %Y"

    social_links:
        twitter: HAAANBIN
        github: hanbin973

    # disqus and google anal
    disqus_shortname: hanbin973 
    analytics_id: '128593793'

# Site settings
title: Hanbin Lee
email: hanbin973@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hanbin973.github.io" # the base hostname & protocol for your site
twitter_username: @HAAANBIN
github_username:  hanbin973

# Build settings
markdown: kramdown
